name: check-housing

# on:
# schedule:
 #   - cron: "7,37 * * * *"
  #workflow_dispatch:

#permissions:
#  contents: read
 # actions: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore housing_db.json (from previous runs)
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: .github/workflows/main.yml
          workflow_conclusion: success
          branch: ${{ github.ref_name }}
          name: housing-db
          path: .
        continue-on-error: true

      - name: Ensure housing_db.json exists
        run: |
          [ -f housing_db.json ] || echo "{}" > housing_db.json
          ls -l housing_db.json

      - name: Run housing watcher
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python watch_housing.py

      - name: Upload housing_db.json
        uses: actions/upload-artifact@v4
        with:
          name: housing-db
          path: housing_db.json
          retention-days: 7
